services:
  aetha-frontend:
    image: nisalwishwajith/aetha-frontend:latest
    # build: ./aetha-frontend
    container_name: aetha-frontend
    networks:
      - app-network
    ports:
      - 4173:4173
  aetha-backend:
    image: nisalwishwajith/aetha-backend:latest
    # build: ./aetha-backend
    container_name: aetha-backend
    networks:
      - app-network
    ports:
      - 8080:8080
networks:
  app-network:
    driver: bridge
