services:
  caddy:
    image: caddy:2.8.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/caddy-conf:/etc/caddy/
      - caddy-conf:/config
      - caddy-data:/data
    networks:
      - app-network
  aetha-frontend:
    build: ./aetha-frontend
    container_name: aetha-frontend
    networks:
      - app-network
  aetha-backend:
    build: ./aetha-backend
    container_name: aetha-backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  caddy-conf:
  caddy-data:
