services:
  aetha-frontend:
    build: ./aetha-frontend
    container_name: aetha-frontend
    networks:
      - app-network
    ports:
      - 4173:4173
  aetha-backend:
    build: ./aetha-backend
    container_name: aetha-backend
    networks:
      - app-network
    ports:
      - 8080:8080
networks:
  app-network:
    driver: bridge